docs, tests, updates, bug fixes, and more
use nixos-unstable channel by default
improved and updated documentation
tested and documented installing on different DO Images
fix install on Debian (requires xz-utils)
fix networking.nix formatting
fix networking.nix (eth1) interface detection
use a few (not all! some are wrong!) shellcheck suggestions

diff --git a/nixos-infect b/nixos-infect
--- a/nixos-infect
+++ b/nixos-infect
@@ -10,8 +10,8 @@ makeConf() {
   # NB <<"EOF" quotes / $ ` in heredocs, <<EOF does not
   mkdir -p /etc/nixos
   # Prevent grep for sending error code 1 (and halting execution) when no lines are selected : https://www.unix.com/man-page/posix/1P/grep
-  local IFS=$'\n' 
-  for trypath in /root/.ssh/authorized_keys $HOME/.ssh/authorized_keys; do 
+  local IFS=$'\n'
+  for trypath in /root/.ssh/authorized_keys $HOME/.ssh/authorized_keys; do
       [[ -r "$trypath" ]] \
       && keys=$(sed -E 's/^.*((ssh|ecdsa)-[^[:space:]]+)[[:space:]]+([^[:space:]]+)([[:space:]]*.*)$/\1 \3\4/' "$trypath") \
       && break
@@ -19,7 +19,7 @@ makeConf() {
   local network_import=""
 
   [ "$PROVIDER" = "digitalocean" ] && network_import="./networking.nix # generated at runtime by nixos-infect"
-  cat > /etc/nixos/configuration.nix << EOF
+  cat > /etc/nixos/configuration.nix <<EOF
 { ... }: {
   imports = [
     ./hardware-configuration.nix
@@ -37,7 +37,7 @@ makeConf() {
 }
 EOF
   # If you rerun this later, be sure to prune the filesSystems attr
-  cat > /etc/nixos/hardware-configuration.nix << EOF
+  cat > /etc/nixos/hardware-configuration.nix <<EOF
 { ... }:
 {
   imports = [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix> ];
@@ -64,33 +64,52 @@ makeNetworkingConf() {
   gateway6=$(ip -6 route show dev "$eth0_name" | grep default | sed -r 's|default via ([0-9a-f:]+).*|\1|' || true)
   ether0=$(ip address show dev "$eth0_name" | grep link/ether | sed -r 's|.*link/ether ([0-9a-f:]+) .*|\1|')
 
+# NB double quoting the arrays breaks spacing in networking.nix
+  interfaces0=$(cat <<EOF
+$eth0_name = {
+        ipv4.addresses = [$(for a in ${eth0_ip4s[@]}; do echo -n "
+          $a"; done)
+        ];
+        ipv6.addresses = [$(for a in ${eth0_ip6s[@]}; do echo -n "
+          $a"; done)
+        ];
+        ipv4.routes = [ { address = "${gateway}"; prefixLength = 32; } ];
+        ipv6.routes = [ { address = "${gateway6}"; prefixLength = 32; } ];
+      };
+EOF
+)
+
   eth1_name=$(ip address show | grep '^3:' | awk -F': ' '{print $2}')||true
   if [ -n "$eth1_name" ];then
     eth1_ip4s=$(ip address show dev "$eth1_name" | grep 'inet ' | sed -r 's|.*inet ([0-9.]+)/([0-9]+).*|{ address="\1"; prefixLength=\2; }|')
     eth1_ip6s=$(ip address show dev "$eth1_name" | grep 'inet6 ' | sed -r 's|.*inet6 ([0-9a-f:]+)/([0-9]+).*|{ address="\1"; prefixLength=\2; }|' || '')
     ether1=$(ip address show dev "$eth1_name" | grep link/ether | sed -r 's|.*link/ether ([0-9a-f:]+) .*|\1|')
-    interfaces1=<< EOF
-      $eth1_name = {
-        ipv4.addresses = [$(for a in "${eth1_ip4s[@]}"; do echo -n "
+# NB double quoting the arrays breaks spacing
+    interfaces1=$(cat <<EOF
+$eth1_name = {
+        ipv4.addresses = [$(for a in ${eth1_ip4s[@]}; do echo -n "
           $a"; done)
         ];
-        ipv6.addresses = [$(for a in "${eth1_ip6s[@]}"; do echo -n "
+        ipv6.addresses = [$(for a in ${eth1_ip6s[@]}; do echo -n "
           $a"; done)
         ];
+      };
 EOF
+)
     extraRules1="ATTR{address}==\"${ether1}\", NAME=\"${eth1_name}\""
   else
     interfaces1=""
     extraRules1=""
   fi
 
+# NB double quoting the arrays breaks spacing in networking.nix
   nameservers=($(grep ^nameserver /etc/resolv.conf | cut -f2 -d' '))
-  if [ "$eth0_name" = eth* ]; then
+  if [[ "$eth0_name" = eth* ]]; then
     predictable_inames="usePredictableInterfaceNames = lib.mkForce false;"
   else
     predictable_inames="usePredictableInterfaceNames = lib.mkForce true;"
   fi
-  cat > /etc/nixos/networking.nix << EOF
+  cat > /etc/nixos/networking.nix <<EOF
 { lib, ... }: {
   # This file was populated at runtime with the networking
   # details gathered from the active system.
@@ -103,16 +122,7 @@ EOF
     dhcpcd.enable = false;
     $predictable_inames
     interfaces = {
-      $eth0_name = {
-        ipv4.addresses = [$(for a in "${eth0_ip4s[@]}"; do echo -n "
-          $a"; done)
-        ];
-        ipv6.addresses = [$(for a in "${eth0_ip6s[@]}"; do echo -n "
-          $a"; done)
-        ];
-        ipv4.routes = [ { address = "${gateway}"; prefixLength = 32; } ];
-        ipv6.routes = [ { address = "${gateway6}"; prefixLength = 32; } ];
-      };
+      $interfaces0
       $interfaces1
     };
   };
@@ -164,7 +174,7 @@ prepareEnv() {
   export HOME="/root"
 
   # Use adapted wget if curl is missing
-  which curl || { \
+  command -v curl || { \
     curl() {
       eval "wget $(
         (local isStdout=1
@@ -196,32 +206,34 @@ prepareEnv() {
 }
 
 req() {
-  type "$1" > /dev/null 2>&1 || which "$1" > /dev/null 2>&1
+  type "$1" > /dev/null 2>&1 || command -v "$1" > /dev/null 2>&1
 }
 
 checkEnv() {
   # Perform some easy fixups before checking
-  which dnf && dnf install -y perl-Digest-SHA # Fedora 24
-  which bzcat || (which yum && yum install -y bzip2) \
-              || (which apt-get && apt-get update && apt-get install -y bzip2) \
+  command -v dnf && dnf install -y perl-Digest-SHA # Fedora 24
+  command -v bzcat || (command -v yum && yum install -y bzip2) \
+              || (command -v apt-get && apt-get update && apt-get install -y bzip2) \
               || true
+  command -v xz || (command -v apt-get && apt-get update && apt-get install -y xz-utils)
 
   [[ "$(whoami)" == "root" ]] || { echo "ERROR: Must run as root"; return 1; }
 
-  req curl || req wget || { echo "ERROR: Missing both curl and wget"; return 1; }
-  req bzcat            || { echo "ERROR: Missing bzcat";              return 1; }
-  req groupadd         || { echo "ERROR: Missing groupadd";           return 1; }
-  req useradd          || { echo "ERROR: Missing useradd";            return 1; }
-  req ip               || { echo "ERROR: Missing ip";                 return 1; }
   req awk              || { echo "ERROR: Missing awk";                return 1; }
+  req bzcat            || { echo "ERROR: Missing bzcat";              return 1; }
+  req curl || req wget || { echo "ERROR: Missing both curl and wget"; return 1; }
   req cut              || { echo "ERROR: Missing cut";                return 1; }
+  req groupadd         || { echo "ERROR: Missing groupadd";           return 1; }
+  req ip               || { echo "ERROR: Missing ip";                 return 1; }
+  req useradd          || { echo "ERROR: Missing useradd";            return 1; }
+  req xz               || { echo "ERROR: Missing xz";                 return 1; }
 }
 
 infect() {
   # Add nix build users
   # FIXME run only if necessary, rather than defaulting true
   groupadd nixbld -g 30000 || true
-  for i in {1..10}; do useradd -c "Nix build user $i" -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" nixbld$i || true; done
+  for i in {1..10}; do useradd -c "Nix build user $i" -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(command -v nologin)" nixbld$i || true; done
   # TODO use addgroup and adduser as fallbacks
   #addgroup nixbld -g 30000 || true
   #for i in {1..10}; do adduser -DH -G nixbld nixbld$i || true; done
@@ -231,7 +243,7 @@ infect() {
   # shellcheck disable=SC1090
   source ~/.nix-profile/etc/profile.d/nix.sh
 
-  [[ -z "$NIX_CHANNEL" ]] && NIX_CHANNEL="nixos-19.09"
+  [[ -z "$NIX_CHANNEL" ]] && NIX_CHANNEL="nixos-unstable"
   nix-channel --remove nixpkgs
   nix-channel --add "https://nixos.org/channels/$NIX_CHANNEL" nixos
   nix-channel --update
