Add EFI support

diff --git a/nixos-infect b/nixos-infect
--- a/nixos-infect
+++ b/nixos-infect
@@ -36,12 +36,30 @@ makeConf() {
   ];
 }
 EOF
+
+  if isEFI; then
+    bootcfg=$(cat << EOF
+  boot.loader.grub = {
+    efiSupport = true;
+    efiInstallAsRemovable = true;
+    device = "nodev";
+  };
+  fileSystems."/boot" = { device = "$esp"; fsType = "vfat"; };
+EOF
+)
+  else
+    bootcfg=$(cat << EOF
+  boot.loader.grub.device = "$grubdev";
+EOF
+)
+  fi
+
   # If you rerun this later, be sure to prune the filesSystems attr
   cat > /etc/nixos/hardware-configuration.nix << EOF
 { modulesPath, ... }:
 {
   imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
-  boot.loader.grub.device = "$grubdev";
+$bootcfg
   boot.initrd.kernelModules = [ "nvme" ];
   fileSystems."/" = { device = "$rootfsdev"; fsType = "ext4"; };
 }
@@ -136,9 +154,31 @@ removeSwap() {
   rm -vf /tmp/nixos-infect.*.swp
 }
 
+isEFI() {
+  [ -d /sys/firmware/efi ]
+}
+
+findESP() {
+  esp=""
+  for d in /boot/EFI /boot/efi /boot; do
+    [[ ! -d "$d" ]] && continue
+    [[ "$d" == "$(df "$d" --output=target | sed 1d)" ]] \
+      && esp="$(df "$d" --output=source | sed 1d)" \
+      && break
+  done
+  [[ -z "$esp" ]] && { echo "ERROR: No ESP mount point found"; return 1; }
+  for uuid in /dev/disk/by-uuid/*; do
+    [[ $(readlink -f "$uuid") == "$esp" ]] && echo $uuid && return 0
+  done
+}
+
 prepareEnv() {
-  # $grubdev is used in makeConf()
-  for grubdev in /dev/vda /dev/sda /dev/nvme0n1 ; do [[ -e $grubdev ]] && break; done
+  # $esp and $grubdev are used in makeConf()
+  if isEFI; then
+    esp="$(findESP)"
+  else
+    for grubdev in /dev/vda /dev/sda /dev/nvme0n1 ; do [[ -e $grubdev ]] && break; done
+  fi
 
   # Retrieve root fs block device
   #                   (get root mount)  (get partition or logical volume)
@@ -202,14 +242,14 @@ checkEnv() {
               || (which apt-get && apt-get update && apt-get install -y curl) \
               || true
 
-  req curl || req wget || { echo "ERROR: Missing both curl and wget"; return 1; }
-  req bzcat            || { echo "ERROR: Missing bzcat";              return 1; }
-  req xzcat            || { echo "ERROR: Missing xzcat";              return 1; }
-  req groupadd         || { echo "ERROR: Missing groupadd";           return 1; }
-  req useradd          || { echo "ERROR: Missing useradd";            return 1; }
-  req ip               || { echo "ERROR: Missing ip";                 return 1; }
-  req awk              || { echo "ERROR: Missing awk";                return 1; }
-  req cut              || { echo "ERROR: Missing cut";                return 1; }
+  req curl || req wget || { echo "ERROR: Missing both curl and wget";  return 1; }
+  req bzcat            || { echo "ERROR: Missing bzcat";               return 1; }
+  req xzcat            || { echo "ERROR: Missing xzcat";               return 1; }
+  req groupadd         || { echo "ERROR: Missing groupadd";            return 1; }
+  req useradd          || { echo "ERROR: Missing useradd";             return 1; }
+  req ip               || { echo "ERROR: Missing ip";                  return 1; }
+  req awk              || { echo "ERROR: Missing awk";                 return 1; }
+  req cut || req df    || { echo "ERROR: Missing coreutils (cut, df)"; return 1; }
 }
 
 infect() {
@@ -255,7 +295,13 @@ infect() {
   echo root/.nix-defexpr/channels >> /etc/NIXOS_LUSTRATE
 
   rm -rf /boot.bak
+  isEFI && umount "$esp"
   mv -v /boot /boot.bak
+  if isEFI; then
+    mkdir /boot
+    mount "$esp" /boot
+    find /boot -depth ! -path /boot -exec rm -rf {} +
+  fi
   /nix/var/nix/profiles/system/bin/switch-to-configuration boot
 }
 
